const defaultTransactions = [
  {id:1,type:"expense",amount:42.50,category:"Food",note:"Sunday brunch",date:"2024-10-13"},
  {id:2,type:"expense",amount:18.00,category:"Transport",note:"Metro card",date:"2024-10-12"},
  {id:3,type:"income",amount:2400,category:"Salary",note:"October salary",date:"2024-10-01"},
  {id:4,type:"expense",amount:84.20,category:"Shopping",note:"Home supplies",date:"2024-09-29"},
  {id:5,type:"expense",amount:12.50,category:"Entertainment",note:"Movie night",date:"2024-09-27"}
];
const state = {page:"overview", authMode:"login", currency:"INR", transactions:JSON.parse(localStorage.getItem("spendwise_transactions")||"null")||defaultTransactions, user:JSON.parse(localStorage.getItem("spendwise_user")||"null")||null, editType:"expense"};
const $ = s => document.querySelector(s);
const money = n => new Intl.NumberFormat("en-IN",{style:"currency",currency:state.currency,maximumFractionDigits:2}).format(n);
const icons = {Food:"◉",Transport:"⌁",Housing:"⌂",Shopping:"◇",Health:"✚",Entertainment:"♫",Salary:"↗",Other:"•"};
function save(){localStorage.setItem("spendwise_transactions",JSON.stringify(state.transactions));}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2600)}
function initials(name){return (name||"Alex Morgan").split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase()}
function showAuth(){ $("#authView").classList.remove("hidden"); $("#appView").classList.add("hidden"); }
function showApp(){ $("#authView").classList.add("hidden"); $("#appView").classList.remove("hidden"); const name=state.user.name; $("#sideName").textContent=name; $("#sideEmail").textContent=state.user.email; $("#avatar").textContent=initials(name); $("#mobileProfile").textContent=initials(name); renderPage(); }
function total(type){return state.transactions.filter(t=>t.type===type).reduce((a,t)=>a+t.amount,0)}
function dateLabel(date){return new Date(date+"T12:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric"})}
function transactionRow(t,actions=false){return `<div class="transaction"><div class="category-icon">${icons[t.category]||"•"}</div><div class="transaction-info"><strong>${t.note||t.category}</strong><small>${t.category} · ${dateLabel(t.date)}</small></div><div class="amount ${t.type}">${t.type==="income"?"+":"-"}${money(t.amount)}</div>${actions?`<button class="link-button edit-transaction" data-id="${t.id}">Edit</button><button class="link-button delete-transaction" data-id="${t.id}">Delete</button>`:""}</div>`}
function renderPage(){
 const name=state.user.name.split(" ")[0]; const titles={overview:`Good morning, ${name}`,transactions:"Transactions",budgets:"Budgets",insights:"Your insights",settings:"Settings"}; $("#pageTitle").textContent=titles[state.page]; $("#pageKicker").textContent=new Date().toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"}).toUpperCase(); $(".nav-item.active")?.classList.remove("active"); document.querySelector(`[data-page="${state.page}"]`)?.classList.add("active");
 const pages={overview:overviewPage,transactions:transactionsPage,budgets:budgetsPage,insights:insightsPage,settings:settingsPage}; $("#pageContent").innerHTML=pages[state.page](); bindPageEvents();
}
function overviewPage(){const inc=total("income"), exp=total("expense"), balance=inc-exp; const recent=state.transactions.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4); return `<section class="grid stats-grid"><div class="card stat-card"><span class="label">Total balance</span><div class="value">${money(balance)}</div><span class="trend">↑ 8.4% this month</span></div><div class="card stat-card"><span class="label">Income</span><div class="value">${money(inc)}</div><span class="trend">↑ 12.1% this month</span></div><div class="card stat-card"><span class="label">Expenses</span><div class="value">${money(exp)}</div><span class="trend down">↓ 3.2% this month</span></div><div class="card stat-card"><span class="label">Savings rate</span><div class="value">${inc?Math.round((balance/inc)*100):0}%</div><span class="trend">Great progress!</span></div></section><section class="grid overview-grid"><div class="card"><div class="card-head"><div><h3>Spending overview</h3><p>Last 7 months</p></div><button class="pill-button">Monthly ⌄</button></div><div class="chart-wrap">${[45,62,42,78,56,70,88].map((v,i)=>`<div class="bar ${i===6?"active":""}" style="height:${v}%"><span>${["Apr","May","Jun","Jul","Aug","Sep","Oct"][i]}</span></div>`).join("")}</div></div><div class="card"><div class="card-head"><div><h3>By category</h3><p>This month</p></div><button class="link-button" data-page-link="insights">See all →</button></div><div class="donut-row"><div class="donut"></div><div class="legend"><div class="legend-item"><i class="dot"></i><span>Food</span><strong>42%</strong></div><div class="legend-item"><i class="dot mint"></i><span>Transport</span><strong>25%</strong></div><div class="legend-item"><i class="dot orange"></i><span>Shopping</span><strong>17%</strong></div><div class="legend-item"><i class="dot gray"></i><span>Other</span><strong>16%</strong></div></div></div></div></section><div class="section-title"><h3>Recent transactions</h3><button class="link-button" data-page-link="transactions">View all →</button></div><div class="card transaction-list">${recent.map(t=>transactionRow(t)).join("")}</div>`}
function transactionsPage(){return `<div class="section-title"><div><h3>All transactions</h3><p class="muted">A complete view of your money movement.</p></div><button class="primary" id="addTransaction">＋ Add transaction</button></div><div class="toolbar"><input id="searchTransactions" placeholder="Search transactions…"><select id="filterType"><option value="all">All types</option><option value="expense">Expenses</option><option value="income">Income</option></select><select id="filterCategory"><option value="all">All categories</option>${Object.keys(icons).map(c=>`<option>${c}</option>`).join("")}</select></div><div class="card transaction-list" id="transactionResults">${state.transactions.length?state.transactions.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(t=>transactionRow(t,true)).join(""):`<div class="empty"><strong>No transactions yet</strong>Add your first transaction to start.</div>`}</div>`}
function budgetsPage(){return `<div class="section-title"><div><h3>Monthly budgets</h3><p class="muted">Keep your priorities visible.</p></div><button class="primary" id="notifyButton">Enable reminders</button></div><div class="budget-list">${[["Food",350,242],["Transport",180,96],["Shopping",250,212],["Entertainment",120,58],["Health",150,30],["Housing",1200,950]].map(([c,max,used])=>`<div class="card"><div class="card-head"><div><h3>${icons[c]} &nbsp;${c}</h3><p>October budget</p></div><button class="link-button">•••</button></div><div class="progress"><i class="${used/max>.85?"warning":""}" style="width:${Math.min(100,used/max*100)}%"></i></div><div class="budget-meta"><span>${money(used)} spent</span><strong>${money(max-used)} left</strong></div></div>`).join("")}</div>`}
function insightsPage(){return `<div class="section-title"><div><h3>Personalized insights</h3><p class="muted">Simple observations from your spending.</p></div><button class="pill-button" id="rateButton">Refresh rates ↻</button></div><div class="grid" style="gap:12px"><div class="card insight"><div class="insight-icon">✦</div><div><h3>You are spending less on transport</h3><p class="muted">Your transport spending is down 18% compared with last month. Keep it up!</p></div></div><div class="card insight"><div class="insight-icon">◒</div><div><h3>Food is your biggest category</h3><p class="muted">You have used 69% of your food budget. There are 12 days left in the month.</p></div></div><div class="card insight"><div class="insight-icon">↗</div><div><h3>Try a weekly savings goal</h3><p class="muted">Saving ${money(40)} each week could build a ${money(2080)} cushion this year.</p></div></div></div><div id="rateResult" class="card hidden" style="margin-top:18px"></div>`}
function settingsPage(){return `<div class="card"><div class="card-head"><div><h3>Profile</h3><p>Manage your account details.</p></div></div><label>Display name<input id="settingsName" value="${state.user.name}"></label><label>Email<input value="${state.user.email}" disabled></label><button class="primary" id="saveProfile">Save profile <span>→</span></button></div><div class="card" style="margin-top:18px"><div class="card-head"><div><h3>Device integrations</h3><p>Connect SpendWise to your device.</p></div></div><button class="pill-button" id="cameraButton">📷 Add receipt photo</button><input id="cameraInput" type="file" accept="image/*" capture="environment" class="hidden"><p class="muted" style="font-size:12px">Camera access is requested only when you choose to add a receipt.</p></div>`}
function bindPageEvents(){document.querySelectorAll("[data-page-link]").forEach(b=>b.onclick=()=>{state.page=b.dataset.page;renderPage()}); $("#addTransaction")?.addEventListener("click",()=>openModal()); $("#searchTransactions")?.addEventListener("input",filterTransactions); $("#filterType")?.addEventListener("change",filterTransactions); $("#filterCategory")?.addEventListener("change",filterTransactions); document.querySelectorAll(".delete-transaction").forEach(b=>b.onclick=()=>{state.transactions=state.transactions.filter(t=>String(t.id)!==b.dataset.id);save();renderPage();toast("Transaction deleted")}); document.querySelectorAll(".edit-transaction").forEach(b=>b.onclick=()=>openModal(state.transactions.find(t=>String(t.id)===b.dataset.id))); $("#notifyButton")?.addEventListener("click",async()=>{if(!("Notification" in window)){toast("Notifications are not supported here");return} const result=await Notification.requestPermission();toast(result==="granted"?"Reminders enabled":"Permission was not granted")}); $("#rateButton")?.addEventListener("click",fetchRates); $("#saveProfile")?.addEventListener("click",()=>{state.user.name=$("#settingsName").value.trim()||state.user.name;localStorage.setItem("spendwise_user",JSON.stringify(state.user));showApp();toast("Profile updated")}); $("#cameraButton")?.addEventListener("click",()=>$("#cameraInput").click()); $("#cameraInput")?.addEventListener("change",()=>toast("Receipt photo added to this session"))}
function filterTransactions(){const q=($("#searchTransactions").value||"").toLowerCase(), type=$("#filterType").value, cat=$("#filterCategory").value; const list=state.transactions.filter(t=>(!q||`${t.note} ${t.category}`.toLowerCase().includes(q))&&(type==="all"||t.type===type)&&(cat==="all"||t.category===cat)); $("#transactionResults").innerHTML=list.length?list.map(t=>transactionRow(t,true)).join(""):`<div class="empty"><strong>No matches found</strong>Try another search or filter.</div>`;bindPageEvents()}
async function fetchRates(){const box=$("#rateResult");box.classList.remove("hidden");box.innerHTML="Loading current exchange rates…";try{const response=await fetch("https://open.er-api.com/v6/latest/INR");if(!response.ok)throw new Error("rate request failed");const data=await response.json();box.innerHTML=`<h3>Live exchange rates</h3><p class="muted">1 INR = ${data.rates.USD.toFixed(4)} USD · ${data.rates.EUR.toFixed(4)} EUR · ${data.rates.GBP.toFixed(4)} GBP</p>`}catch(e){box.innerHTML="<h3>Rates unavailable</h3><p class='muted'>Please check your connection and try again.</p>"}}
function openModal(t=null){$("#transactionModal").classList.remove("hidden");$("#modalTitle").textContent=t?"Edit transaction":"Add transaction";$("#transactionId").value=t?.id||"";$("#amountInput").value=t?.amount||"";$("#categoryInput").value=t?.category||"Food";$("#dateInput").value=t?.date||new Date().toISOString().slice(0,10);$("#noteInput").value=t?.note||"";state.editType=t?.type||"expense";document.querySelectorAll(".type-toggle button").forEach(b=>b.classList.toggle("active",b.dataset.type===state.editType))}
function closeModal(){$("#transactionModal").classList.add("hidden")}
document.querySelectorAll("[data-auth]").forEach(b=>b.onclick=()=>{state.authMode=b.dataset.auth;document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));$("#nameField").classList.toggle("hidden",state.authMode==="login");$("#authSubmit").textContent=state.authMode==="login"?"Continue":"Create account"});
$("#authForm").onsubmit=e=>{e.preventDefault();const email=$("#emailInput").value.trim(),password=$("#passwordInput").value;if(password.length<6){toast("Password must be at least 6 characters");return}state.user={name:state.authMode==="register"?($("#nameInput").value.trim()||"Alex Morgan"):"Alex Morgan",email};localStorage.setItem("spendwise_user",JSON.stringify(state.user));showApp();toast(state.authMode==="login"?"Welcome back!":"Account created successfully")};
$("#demoLogin").onclick=()=>{state.user={name:"Alex Morgan",email:"alex@spendwise.demo"};localStorage.setItem("spendwise_user",JSON.stringify(state.user));showApp();toast("Demo account loaded")};
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{state.page=b.dataset.page;renderPage();$(".sidebar").classList.remove("open")});
$("#logout").onclick=()=>{state.user=null;showAuth();toast("You have been logged out")};$("#menuButton").onclick=()=>$(".sidebar").classList.toggle("open");$("#mobileProfile").onclick=()=>{state.page="settings";renderPage()};
document.querySelector(".close-modal").onclick=closeModal;$("#transactionModal").onclick=e=>{if(e.target.id==="transactionModal")closeModal()};document.querySelectorAll(".type-toggle button").forEach(b=>b.onclick=()=>{state.editType=b.dataset.type;document.querySelectorAll(".type-toggle button").forEach(x=>x.classList.toggle("active",x===b))});
$("#transactionForm").onsubmit=e=>{e.preventDefault();const item={id:$("#transactionId").value?Number($("#transactionId").value):Date.now(),type:state.editType,amount:Number($("#amountInput").value),category:$("#categoryInput").value,note:$("#noteInput").value.trim()||$("#categoryInput").value,date:$("#dateInput").value};const index=state.transactions.findIndex(t=>t.id===item.id);if(index>=0)state.transactions[index]=item;else state.transactions.push(item);save();closeModal();renderPage();toast(index>=0?"Transaction updated":"Transaction saved")};
$("#startApp").onclick=()=>{localStorage.setItem("spendwise_onboarded","1");$("#introView").classList.add("hidden");showAuth()};
if(state.user)showApp();else if(!localStorage.getItem("spendwise_onboarded")){$("#authView").classList.add("hidden");$("#introView").classList.remove("hidden")}
